---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattermod

bases:
  - ../../base/app
  - ../../base/jobserver
  - ../../base/config

resources:
  - ingress.yaml
  - pvc.yaml

patchesStrategicMerge:
  # - patches/deployment-replicas.yaml
  - patches/deployment-data-pvc.yaml
  - patches/deployment-gitconfig.yaml

secretGenerator:
  - name: gitconfig
    files:
      - ssh/id_rsa
      - ssh/config
      - ssh/known_hosts

images:
  - name: mattermost/mattermod
    newName: mattermost/mattermod
    newTag: 0.20.0
  - name: mattermost/mattermod-jobserver
    newName: mattermost/mattermod-jobserver
    newTag: 0.20.0
