---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattermod

bases:
  - ../../base/app
  - ../../base/db
  - ../../base/config

resources:
  - ingress.yaml

patchesStrategicMerge:
  - patches/deployment-replicas.yaml
  - patches/database-pvc.yaml

secretGenerator:
  - name: mysql
    behavior: replace
    envs:
      - env.sh
    type: Opaque

configMapGenerator:
  - name: config
    behavior: merge
    files:
      - instance-setup-mattermost-server
      - instance-setup-mattermost-webapp
      - instance-setup-upgrade-mattermost-server
      - test.spinmint.com.fullchain.pem
      - test.spinmint.com.privkey.pem

images:
  - name: mattermost/mattermod
    newName: mattermost/mattermod
    newTag: 0.1.0
