---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - pvc.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: mattermod
  component: db
