run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mattermost/mattermod
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude:
    # github.com/go-gorp/gorp.TypeConverter isn't golint compliant
    - "ST1003: method ToDb should be ToDB"
    - "ST1003: method FromDb should be FromD"
    # For executing git commands.
    - "G204: Subprocess launched with function call as argument or cmd arguments"

  exclude-rules:
    - linters:
      - goconst
      # Ignore warnings trying to change variables to constants.
      # We can't do that because we are taking the address of those variables.
      path: "issue_handler_test.go"
