version: '2.4'
services:
  web:
    build:
      context: .
      dockerfile: $PWD/Dockerfile.test
    container_name: mattermod
    command: make test
    networks:
      default:
        aliases:
          - web
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mattermod
      MYSQL_USER: mattermod
      MYSQL_PASSWORD: mattermod
      MYSQL_DATABASE: mattermod
    networks:
      default:
        aliases:
          - mysql

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep
    depends_on:
      - db
    command: mysql:3306
    networks:
      default:

networks:
  default:
    external:
      name: $DOCKER_NETWORK
