---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    files:
      - config-mattermod.json
      - config-jobserver.json

commonLabels:
  app: mattermod
