---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermod
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: config
            items:
              - key: config.json
                path: config.json
              - key: instance-setup-mattermost-server
                path: instance-setup-mattermost-server
              - key: instance-setup-mattermost-webapp
                path: instance-setup-mattermost-webapp
              - key: instance-setup-upgrade-mattermost-server
                path: instance-setup-upgrade-mattermost-server
              - key: test.spinmint.com.fullchain.pem
                path: test.spinmint.com.fullchain.pem
              - key: test.spinmint.com.privkey.pem
                path: test.spinmint.com.privkey.pem
