version: 2.1

orbs:
  tools: gotest/tools@0.0.13

executors:
  default:
    docker:
      - image: circleci/golang:1.14

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - tools/install-golangci-lint:
          version: "1.24.0"
      - run: make check-style

  build:
    executor:
      name: default
    steps:
      - checkout
      - run: make build

  test:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mattermod
          MYSQL_DATABASE: mattermod
          MYSQL_USER: mattermod
          MYSQL_PASSWORD: mattermod
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
