// Code generated by MockGen. DO NOT EDIT.
// Source: store/store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/mattermost/mattermost-mattermod/model"
	store "github.com/mattermost/mattermost-mattermod/store"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStore) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// DropAllTables mocks base method.
func (m *MockStore) DropAllTables() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DropAllTables")
}

// DropAllTables indicates an expected call of DropAllTables.
func (mr *MockStoreMockRecorder) DropAllTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropAllTables", reflect.TypeOf((*MockStore)(nil).DropAllTables))
}

// Issue mocks base method.
func (m *MockStore) Issue() store.IssueStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue")
	ret0, _ := ret[0].(store.IssueStore)
	return ret0
}

// Issue indicates an expected call of Issue.
func (mr *MockStoreMockRecorder) Issue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockStore)(nil).Issue))
}

// PullRequest mocks base method.
func (m *MockStore) PullRequest() store.PullRequestStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullRequest")
	ret0, _ := ret[0].(store.PullRequestStore)
	return ret0
}

// PullRequest indicates an expected call of PullRequest.
func (mr *MockStoreMockRecorder) PullRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullRequest", reflect.TypeOf((*MockStore)(nil).PullRequest))
}

// Spinmint mocks base method.
func (m *MockStore) Spinmint() store.SpinmintStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spinmint")
	ret0, _ := ret[0].(store.SpinmintStore)
	return ret0
}

// Spinmint indicates an expected call of Spinmint.
func (mr *MockStoreMockRecorder) Spinmint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spinmint", reflect.TypeOf((*MockStore)(nil).Spinmint))
}

// MockPullRequestStore is a mock of PullRequestStore interface.
type MockPullRequestStore struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestStoreMockRecorder
}

// MockPullRequestStoreMockRecorder is the mock recorder for MockPullRequestStore.
type MockPullRequestStoreMockRecorder struct {
	mock *MockPullRequestStore
}

// NewMockPullRequestStore creates a new mock instance.
func NewMockPullRequestStore(ctrl *gomock.Controller) *MockPullRequestStore {
	mock := &MockPullRequestStore{ctrl: ctrl}
	mock.recorder = &MockPullRequestStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestStore) EXPECT() *MockPullRequestStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPullRequestStore) Get(repoOwner, repoName string, number int) (*model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", repoOwner, repoName, number)
	ret0, _ := ret[0].(*model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPullRequestStoreMockRecorder) Get(repoOwner, repoName, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPullRequestStore)(nil).Get), repoOwner, repoName, number)
}

// ListOpen mocks base method.
func (m *MockPullRequestStore) ListOpen() ([]*model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOpen")
	ret0, _ := ret[0].([]*model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOpen indicates an expected call of ListOpen.
func (mr *MockPullRequestStoreMockRecorder) ListOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOpen", reflect.TypeOf((*MockPullRequestStore)(nil).ListOpen))
}

// Save mocks base method.
func (m *MockPullRequestStore) Save(pr *model.PullRequest) (*model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", pr)
	ret0, _ := ret[0].(*model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockPullRequestStoreMockRecorder) Save(pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPullRequestStore)(nil).Save), pr)
}

// MockIssueStore is a mock of IssueStore interface.
type MockIssueStore struct {
	ctrl     *gomock.Controller
	recorder *MockIssueStoreMockRecorder
}

// MockIssueStoreMockRecorder is the mock recorder for MockIssueStore.
type MockIssueStoreMockRecorder struct {
	mock *MockIssueStore
}

// NewMockIssueStore creates a new mock instance.
func NewMockIssueStore(ctrl *gomock.Controller) *MockIssueStore {
	mock := &MockIssueStore{ctrl: ctrl}
	mock.recorder = &MockIssueStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueStore) EXPECT() *MockIssueStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIssueStore) Get(repoOwner, repoName string, number int) (*model.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", repoOwner, repoName, number)
	ret0, _ := ret[0].(*model.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueStoreMockRecorder) Get(repoOwner, repoName, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueStore)(nil).Get), repoOwner, repoName, number)
}

// Save mocks base method.
func (m *MockIssueStore) Save(issue *model.Issue) (*model.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", issue)
	ret0, _ := ret[0].(*model.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIssueStoreMockRecorder) Save(issue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIssueStore)(nil).Save), issue)
}

// MockSpinmintStore is a mock of SpinmintStore interface.
type MockSpinmintStore struct {
	ctrl     *gomock.Controller
	recorder *MockSpinmintStoreMockRecorder
}

// MockSpinmintStoreMockRecorder is the mock recorder for MockSpinmintStore.
type MockSpinmintStoreMockRecorder struct {
	mock *MockSpinmintStore
}

// NewMockSpinmintStore creates a new mock instance.
func NewMockSpinmintStore(ctrl *gomock.Controller) *MockSpinmintStore {
	mock := &MockSpinmintStore{ctrl: ctrl}
	mock.recorder = &MockSpinmintStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpinmintStore) EXPECT() *MockSpinmintStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSpinmintStore) Delete(instanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSpinmintStoreMockRecorder) Delete(instanceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpinmintStore)(nil).Delete), instanceID)
}

// Get mocks base method.
func (m *MockSpinmintStore) Get(prNumber int, repoName string) (*model.Spinmint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", prNumber, repoName)
	ret0, _ := ret[0].(*model.Spinmint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSpinmintStoreMockRecorder) Get(prNumber, repoName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSpinmintStore)(nil).Get), prNumber, repoName)
}

// List mocks base method.
func (m *MockSpinmintStore) List() ([]*model.Spinmint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*model.Spinmint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSpinmintStoreMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSpinmintStore)(nil).List))
}

// Save mocks base method.
func (m *MockSpinmintStore) Save(spinmint *model.Spinmint) (*model.Spinmint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", spinmint)
	ret0, _ := ret[0].(*model.Spinmint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSpinmintStoreMockRecorder) Save(spinmint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSpinmintStore)(nil).Save), spinmint)
}
