---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mattermod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mattermod
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mattermod
subjects:
  - kind: ServiceAccount
    name: mattermod
    namespace: mattermod
roleRef:
  kind: Role
  name: mattermod
  apiGroup: rbac.authorization.k8s.io
