---
apiVersion: v1
kind: Service
metadata:
  name: mattermod
spec:
  type: ClusterIP
  selector:
    app: mattermod
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9000
      targetPort: metrics
