---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermod-jobserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: mattermod
      component: jobserver
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: mattermod
        component: jobserver
    spec:
      serviceAccountName: mattermod
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      restartPolicy: Always
      containers:
        - name: mattermod-jobserver
          image: mattermost/mattermod-jobserver
          imagePullPolicy: IfNotPresent
          command:
            - "jobserver"
            - "-config=/app/config/config.json"
          resources:
            limits:
              cpu: "1"
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 100Mi
          ports:
            - name: metrics
              containerPort: 9000
          volumeMounts:
            - name: config
              mountPath: /app/config/config.json
              subPath: config-jobserver.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
