---
apiVersion: v1
kind: Service
metadata:
  name: mattermod-jobserver
spec:
  type: ClusterIP
  selector:
    app: mattermod
    component: jobserver
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics
